### ISSUE TITLE
Invalid version: 1.0

### ISSUE THREAD

**Issue by arruix** [ABB-Austin/cordova-plugin-indexeddb-async#3]
I'm trying to create a windows application with your plugin but when I want create the windows version using cordova platform add windows in the command line I got this error:

Installing "cordova-plugin-indexeddb-async" for windows
Failed to install 'cordova-plugin-indexeddb-async': TypeError: Invalid Version: 1.0
    at new SemVer (C:\Users\myuser\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\semver\semver.js:293:11)
    at Range.test (C:\Users\myuser\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\semver\semver.js:1036:15)
    at Function.satisfies (C:\Users\myuser\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\semver\semver.js:1085:16)
    at installDependency (C:\Users\myuser\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:563:20)
    at C:\Users\myuser\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:434:32
    at _fulfilled (C:\Users\myuser\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\myuser\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\myuser\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\myuser\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:810:14
    at flush (C:\Users\myuser\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:108:17)
Error: Invalid Version: 1.0.

Cordova version: 7.0.1
Window platform version: 5.0.0
NodeJs version: 6.11.3
npm version: 3.10.10

When I was using the Window platform version 4.x was able to install your plugin.

**Comment by jakedegiovanni** [comment]
@arruix I realise this is pretty old at this point but I've run into the same issue and was wondering if you had found a solution?

EDIT: I seem to have gotten past the issue by changing the plugin version number in plugin.xml of the cordova-plugin-wensql dependency. Changed from version="1.0" to version="1.0.0"
